title: "My IAM Automation Blog"
description: "Scripts and tutorials for IAM automation"
baseurl: ""
url: ""
theme: null
plugins:
  - jekyll-feed
markdown: kramdown
highlighter: rouge
author: Sankar
color_scheme: auto
